name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make pyinstall
      - name: lint
        run: make pylint
      - name: test
        run: make pytest
      - name: format
        run: make pyformat